#ChipScope Core Inserter Project File Version 3.0
#Fri Feb 18 18:39:17 MSK 2022
Project.device.designInputFile=C\:\\Users\\user\\Documents\\MBO53_ver17_laser_update\\MBO53\\MBO_53_top_cs.ngc
Project.device.designOutputFile=C\:\\Users\\user\\Documents\\MBO53_ver17_laser_update\\MBO53\\MBO_53_top_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\user\\Documents\\MBO53_ver17_laser_update\\MBO53\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=5
Project.filter<0>=*rx*
Project.filter<1>=
Project.filter<2>=*er*
Project.filter<3>=er*
Project.filter<4>=er
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=laser_cntrl clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=laser_cntrl laser_on
Project.unit<0>.dataChannel<10>=laser_cntrl uart_tx r_Tx_Data(4)
Project.unit<0>.dataChannel<11>=laser_cntrl uart_tx r_Tx_Data(5)
Project.unit<0>.dataChannel<12>=laser_cntrl uart_tx r_Tx_Data(6)
Project.unit<0>.dataChannel<13>=laser_cntrl uart_tx r_Tx_Data(7)
Project.unit<0>.dataChannel<14>=laser_cntrl uart_rx r_Rx_Data
Project.unit<0>.dataChannel<15>=laser_cntrl uart_tx o_Tx_Serial
Project.unit<0>.dataChannel<16>=laser_cntrl Rx_Byte(0)
Project.unit<0>.dataChannel<17>=laser_cntrl Rx_Byte(1)
Project.unit<0>.dataChannel<18>=laser_cntrl Rx_Byte(2)
Project.unit<0>.dataChannel<19>=laser_cntrl Rx_Byte(3)
Project.unit<0>.dataChannel<1>=laser_cntrl cnt_words(0)
Project.unit<0>.dataChannel<20>=laser_cntrl Rx_Byte(4)
Project.unit<0>.dataChannel<21>=laser_cntrl Rx_Byte(5)
Project.unit<0>.dataChannel<22>=laser_cntrl Rx_Byte(6)
Project.unit<0>.dataChannel<23>=laser_cntrl Rx_Byte(7)
Project.unit<0>.dataChannel<2>=laser_cntrl cnt_words(1)
Project.unit<0>.dataChannel<3>=laser_cntrl cnt_words(2)
Project.unit<0>.dataChannel<4>=laser_cntrl cnt_words(3)
Project.unit<0>.dataChannel<5>=laser_cntrl cnt_words(4)
Project.unit<0>.dataChannel<6>=laser_cntrl uart_tx r_Tx_Data(0)
Project.unit<0>.dataChannel<7>=laser_cntrl uart_tx r_Tx_Data(1)
Project.unit<0>.dataChannel<8>=laser_cntrl uart_tx r_Tx_Data(2)
Project.unit<0>.dataChannel<9>=laser_cntrl uart_tx r_Tx_Data(3)
Project.unit<0>.dataDepth=4096
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=24
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=laser_cntrl laser_on
Project.unit<0>.triggerChannel<1><0>=laser_cntrl laser_on_status
Project.unit<0>.triggerChannel<2><0>=laser_cntrl laser_off_comand
Project.unit<0>.triggerChannel<3><0>=laser_cntrl uart_rx r_Clock_Count(0)
Project.unit<0>.triggerChannel<3><1>=laser_cntrl uart_rx r_Clock_Count(1)
Project.unit<0>.triggerChannel<3><2>=laser_cntrl uart_rx r_Clock_Count(2)
Project.unit<0>.triggerChannel<3><3>=laser_cntrl uart_rx r_Clock_Count(3)
Project.unit<0>.triggerChannel<3><4>=laser_cntrl uart_rx r_Clock_Count(4)
Project.unit<0>.triggerChannel<3><5>=laser_cntrl uart_rx r_Clock_Count(5)
Project.unit<0>.triggerChannel<3><6>=laser_cntrl uart_rx r_Clock_Count(6)
Project.unit<0>.triggerChannel<3><7>=laser_cntrl uart_rx r_Clock_Count(7)
Project.unit<0>.triggerChannel<4><0>=laser_cntrl uart_tx r_Clock_Count(0)
Project.unit<0>.triggerChannel<4><1>=laser_cntrl uart_tx r_Clock_Count(1)
Project.unit<0>.triggerChannel<4><2>=laser_cntrl uart_tx r_Clock_Count(2)
Project.unit<0>.triggerChannel<4><3>=laser_cntrl uart_tx r_Clock_Count(3)
Project.unit<0>.triggerChannel<4><4>=laser_cntrl uart_tx r_Clock_Count(4)
Project.unit<0>.triggerChannel<4><5>=laser_cntrl uart_tx r_Clock_Count(5)
Project.unit<0>.triggerChannel<4><6>=laser_cntrl uart_tx r_Clock_Count(6)
Project.unit<0>.triggerChannel<4><7>=laser_cntrl uart_tx r_Clock_Count(7)
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCount<4>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchCountWidth<4><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerMatchType<4><0>=1
Project.unit<0>.triggerPortCount=5
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortIsData<4>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerPortWidth<1>=1
Project.unit<0>.triggerPortWidth<2>=1
Project.unit<0>.triggerPortWidth<3>=8
Project.unit<0>.triggerPortWidth<4>=8
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
