#ChipScope Core Inserter Project File Version 3.0
#Wed Dec 22 21:29:17 MSK 2021
Project.device.designInputFile=E\:\\Xilinx\\projects\\mbo5_3_tech\\MBO_5_3_FPGA_proj\\MBO53\\MBO_53_top_cs.ngc
Project.device.designOutputFile=E\:\\Xilinx\\projects\\mbo5_3_tech\\MBO_5_3_FPGA_proj\\MBO53\\MBO_53_top_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=E\:\\Xilinx\\projects\\mbo5_3_tech\\MBO_5_3_FPGA_proj\\MBO53\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=10
Project.filter<0>=cnt*
Project.filter<1>=
Project.filter<2>=opora*
Project.filter<3>=*t_acc*
Project.filter<4>=*acc*
Project.filter<5>=*data_in*
Project.filter<6>=*t*
Project.filter<7>=acc*
Project.filter<8>=data*
Project.filter<9>=clk*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=convolution_top clkf
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(7)
Project.unit<0>.dataChannel<10>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(2)
Project.unit<0>.dataChannel<11>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(3)
Project.unit<0>.dataChannel<12>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(4)
Project.unit<0>.dataChannel<13>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(5)
Project.unit<0>.dataChannel<14>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(6)
Project.unit<0>.dataChannel<15>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(7)
Project.unit<0>.dataChannel<16>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(15)
Project.unit<0>.dataChannel<17>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(14)
Project.unit<0>.dataChannel<18>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(13)
Project.unit<0>.dataChannel<19>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(12)
Project.unit<0>.dataChannel<1>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(6)
Project.unit<0>.dataChannel<20>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(11)
Project.unit<0>.dataChannel<21>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(10)
Project.unit<0>.dataChannel<22>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(9)
Project.unit<0>.dataChannel<23>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(8)
Project.unit<0>.dataChannel<24>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(7)
Project.unit<0>.dataChannel<25>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(6)
Project.unit<0>.dataChannel<26>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(5)
Project.unit<0>.dataChannel<27>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(4)
Project.unit<0>.dataChannel<28>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(3)
Project.unit<0>.dataChannel<29>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(2)
Project.unit<0>.dataChannel<2>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(5)
Project.unit<0>.dataChannel<30>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(1)
Project.unit<0>.dataChannel<31>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_OUT_A(0)
Project.unit<0>.dataChannel<32>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(15)
Project.unit<0>.dataChannel<33>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(14)
Project.unit<0>.dataChannel<34>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(13)
Project.unit<0>.dataChannel<35>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(12)
Project.unit<0>.dataChannel<36>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(11)
Project.unit<0>.dataChannel<37>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(10)
Project.unit<0>.dataChannel<38>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(9)
Project.unit<0>.dataChannel<39>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(8)
Project.unit<0>.dataChannel<3>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(4)
Project.unit<0>.dataChannel<40>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(7)
Project.unit<0>.dataChannel<41>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(6)
Project.unit<0>.dataChannel<42>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(5)
Project.unit<0>.dataChannel<43>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(4)
Project.unit<0>.dataChannel<44>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(3)
Project.unit<0>.dataChannel<45>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(2)
Project.unit<0>.dataChannel<46>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(1)
Project.unit<0>.dataChannel<47>=convolution_top GEN_N_BLOCKS[1].CONV_CORE DATA_OUT_A(0)
Project.unit<0>.dataChannel<48>=convolution_top cnt_x_rate(4)
Project.unit<0>.dataChannel<49>=convolution_top cnt_x_rate(3)
Project.unit<0>.dataChannel<4>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(3)
Project.unit<0>.dataChannel<50>=convolution_top cnt_x_rate(2)
Project.unit<0>.dataChannel<51>=convolution_top cnt_x_rate(1)
Project.unit<0>.dataChannel<52>=convolution_top cnt_x_rate(0)
Project.unit<0>.dataChannel<53>=convolution_top data_in_en
Project.unit<0>.dataChannel<54>=convolution_top acc_chA(15)
Project.unit<0>.dataChannel<55>=convolution_top acc_chA(14)
Project.unit<0>.dataChannel<56>=convolution_top acc_chA(13)
Project.unit<0>.dataChannel<57>=convolution_top acc_chA(12)
Project.unit<0>.dataChannel<58>=convolution_top acc_chA(11)
Project.unit<0>.dataChannel<59>=convolution_top acc_chA(10)
Project.unit<0>.dataChannel<5>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(2)
Project.unit<0>.dataChannel<60>=convolution_top acc_chA(9)
Project.unit<0>.dataChannel<61>=convolution_top acc_chA(8)
Project.unit<0>.dataChannel<62>=convolution_top acc_chA(7)
Project.unit<0>.dataChannel<63>=convolution_top acc_chA(6)
Project.unit<0>.dataChannel<64>=convolution_top acc_chA(5)
Project.unit<0>.dataChannel<65>=convolution_top acc_chA(4)
Project.unit<0>.dataChannel<66>=convolution_top acc_chA(3)
Project.unit<0>.dataChannel<67>=convolution_top acc_chA(2)
Project.unit<0>.dataChannel<68>=convolution_top acc_chA(1)
Project.unit<0>.dataChannel<69>=convolution_top acc_chA(0)
Project.unit<0>.dataChannel<6>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(1)
Project.unit<0>.dataChannel<70>=convolution_top CONV_BUFFER wr_en
Project.unit<0>.dataChannel<71>=convolution_top CONV_BUFFER rd_en
Project.unit<0>.dataChannel<72>=convolution_top cnt_x_rate_shift(0)
Project.unit<0>.dataChannel<73>=convolution_top cnt_x_rate_shift(1)
Project.unit<0>.dataChannel<74>=convolution_top cnt_x_rate_shift(2)
Project.unit<0>.dataChannel<75>=convolution_top cnt_x_rate_shift(3)
Project.unit<0>.dataChannel<76>=convolution_top cnt_x_rate_shift(4)
Project.unit<0>.dataChannel<7>=convolution_top GEN_N_BLOCKS[0].CONV_CORE DATA_IN_A(0)
Project.unit<0>.dataChannel<8>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(0)
Project.unit<0>.dataChannel<9>=convolution_top GEN_N_BLOCKS[0].CONV_CORE Q_RAM_D(1)
Project.unit<0>.dataDepth=2048
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=77
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=convolution_top opora_en
Project.unit<0>.triggerChannel<1><0>=convolution_top data_in_en
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerPortCount=2
Project.unit<0>.triggerPortIsData<0>=false
Project.unit<0>.triggerPortIsData<1>=false
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerPortWidth<1>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
