#ChipScope Core Inserter Project File Version 3.0
#Mon Feb 28 17:51:14 MSK 2022
Project.device.designInputFile=C\:\\Users\\User\\Documents\\GitHub\\mbo5_3_tech\\MBO_5_3_FPGA_proj\\MBO53\\MBO_53_top_cs.ngc
Project.device.designOutputFile=C\:\\Users\\User\\Documents\\GitHub\\mbo5_3_tech\\MBO_5_3_FPGA_proj\\MBO53\\MBO_53_top_cs.ngc
Project.device.deviceFamily=13
Project.device.enableRPMs=true
Project.device.outputDirectory=C\:\\Users\\User\\Documents\\GitHub\\mbo5_3_tech\\MBO_5_3_FPGA_proj\\MBO53\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=3
Project.filter<0>=
Project.filter<1>=STATE
Project.filter<2>=wea
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=uart_control clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=uart_control rx_d
Project.unit<0>.dataChannel<10>=uart_control ram_din(1)
Project.unit<0>.dataChannel<11>=uart_control ram_din(2)
Project.unit<0>.dataChannel<12>=uart_control ram_din(3)
Project.unit<0>.dataChannel<13>=uart_control ram_din(4)
Project.unit<0>.dataChannel<14>=uart_control ram_din(5)
Project.unit<0>.dataChannel<15>=uart_control ram_din(6)
Project.unit<0>.dataChannel<16>=uart_control ram_din(7)
Project.unit<0>.dataChannel<17>=uart_control ram_din(8)
Project.unit<0>.dataChannel<18>=uart_control ram_din(9)
Project.unit<0>.dataChannel<19>=uart_control ram_din(10)
Project.unit<0>.dataChannel<1>=uart_control tx_d
Project.unit<0>.dataChannel<20>=uart_control ram_din(11)
Project.unit<0>.dataChannel<21>=uart_control ram_din(12)
Project.unit<0>.dataChannel<22>=uart_control ram_din(13)
Project.unit<0>.dataChannel<23>=uart_control ram_din(14)
Project.unit<0>.dataChannel<24>=uart_control ram_din(15)
Project.unit<0>.dataChannel<25>=uart_control ram_addr(0)
Project.unit<0>.dataChannel<26>=uart_control ram_addr(1)
Project.unit<0>.dataChannel<27>=uart_control ram_addr(2)
Project.unit<0>.dataChannel<28>=uart_control ram_addr(3)
Project.unit<0>.dataChannel<29>=uart_control ram_addr(4)
Project.unit<0>.dataChannel<2>=uart_control UART_STATE(0)
Project.unit<0>.dataChannel<30>=uart_control ram_addr(5)
Project.unit<0>.dataChannel<31>=uart_control ram_addr(6)
Project.unit<0>.dataChannel<32>=uart_control ram_addr(7)
Project.unit<0>.dataChannel<33>=uart_control start_uart_strob
Project.unit<0>.dataChannel<34>=uart_control tx_done
Project.unit<0>.dataChannel<35>=uart_control data_in_reg(0)
Project.unit<0>.dataChannel<36>=uart_control data_in_reg(1)
Project.unit<0>.dataChannel<37>=uart_control data_in_reg(2)
Project.unit<0>.dataChannel<38>=uart_control data_in_reg(3)
Project.unit<0>.dataChannel<39>=uart_control data_in_reg(4)
Project.unit<0>.dataChannel<3>=uart_control UART_STATE(1)
Project.unit<0>.dataChannel<40>=uart_control data_in_reg(5)
Project.unit<0>.dataChannel<41>=uart_control data_in_reg(6)
Project.unit<0>.dataChannel<42>=uart_control data_in_reg(7)
Project.unit<0>.dataChannel<43>=uart_control data_in_reg(8)
Project.unit<0>.dataChannel<44>=uart_control data_in_reg(9)
Project.unit<0>.dataChannel<45>=uart_control data_in_reg(10)
Project.unit<0>.dataChannel<46>=uart_control data_in_reg(11)
Project.unit<0>.dataChannel<47>=uart_control data_in_reg(12)
Project.unit<0>.dataChannel<48>=uart_control data_in_reg(13)
Project.unit<0>.dataChannel<49>=uart_control data_in_reg(14)
Project.unit<0>.dataChannel<4>=uart_control UART_STATE(2)
Project.unit<0>.dataChannel<50>=uart_control data_in_reg(15)
Project.unit<0>.dataChannel<51>=uart_control data_in_reg(16)
Project.unit<0>.dataChannel<52>=uart_control data_in_reg(17)
Project.unit<0>.dataChannel<53>=uart_control data_in_reg(18)
Project.unit<0>.dataChannel<54>=uart_control data_in_reg(19)
Project.unit<0>.dataChannel<55>=uart_control data_in_reg(20)
Project.unit<0>.dataChannel<56>=uart_control data_in_reg(21)
Project.unit<0>.dataChannel<57>=uart_control data_in_reg(22)
Project.unit<0>.dataChannel<58>=uart_control data_in_reg(23)
Project.unit<0>.dataChannel<59>=uart_control data_in_reg(24)
Project.unit<0>.dataChannel<5>=uart_control wea
Project.unit<0>.dataChannel<60>=uart_control data_in_reg(25)
Project.unit<0>.dataChannel<61>=uart_control data_in_reg(26)
Project.unit<0>.dataChannel<62>=uart_control data_in_reg(27)
Project.unit<0>.dataChannel<63>=uart_control data_in_reg(28)
Project.unit<0>.dataChannel<64>=uart_control data_in_reg(29)
Project.unit<0>.dataChannel<65>=uart_control data_in_reg(30)
Project.unit<0>.dataChannel<66>=uart_control data_in_reg(31)
Project.unit<0>.dataChannel<67>=uart_control Rx_Byte(0)
Project.unit<0>.dataChannel<68>=uart_control Rx_Byte(1)
Project.unit<0>.dataChannel<69>=uart_control Rx_Byte(2)
Project.unit<0>.dataChannel<6>=uart_control data_in_counter(0)
Project.unit<0>.dataChannel<70>=uart_control Rx_Byte(3)
Project.unit<0>.dataChannel<71>=uart_control Rx_Byte(4)
Project.unit<0>.dataChannel<72>=uart_control Rx_Byte(5)
Project.unit<0>.dataChannel<73>=uart_control Rx_Byte(6)
Project.unit<0>.dataChannel<74>=uart_control Rx_Byte(7)
Project.unit<0>.dataChannel<75>=uart_control rx_d
Project.unit<0>.dataChannel<76>=uart_control tx_done
Project.unit<0>.dataChannel<77>=uart_control uart_tx i_Tx_Byte(0)
Project.unit<0>.dataChannel<78>=uart_control uart_tx i_Tx_Byte(1)
Project.unit<0>.dataChannel<79>=uart_control uart_tx i_Tx_Byte(2)
Project.unit<0>.dataChannel<7>=uart_control data_in_counter(1)
Project.unit<0>.dataChannel<80>=uart_control uart_tx i_Tx_Byte(3)
Project.unit<0>.dataChannel<81>=uart_control uart_tx i_Tx_Byte(4)
Project.unit<0>.dataChannel<82>=uart_control uart_tx i_Tx_Byte(5)
Project.unit<0>.dataChannel<83>=uart_control uart_tx i_Tx_Byte(6)
Project.unit<0>.dataChannel<84>=uart_control uart_tx i_Tx_Byte(7)
Project.unit<0>.dataChannel<85>=
Project.unit<0>.dataChannel<86>=
Project.unit<0>.dataChannel<87>=
Project.unit<0>.dataChannel<88>=
Project.unit<0>.dataChannel<89>=
Project.unit<0>.dataChannel<8>=uart_control data_in_counter(2)
Project.unit<0>.dataChannel<90>=
Project.unit<0>.dataChannel<9>=uart_control ram_din(0)
Project.unit<0>.dataDepth=512
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=85
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=uart_control wea
Project.unit<0>.triggerChannel<1><0>=uart_control start_uart_strob
Project.unit<0>.triggerChannel<2><0>=uart_control UART_STATE(0)
Project.unit<0>.triggerChannel<2><1>=uart_control UART_STATE(1)
Project.unit<0>.triggerChannel<2><2>=uart_control UART_STATE(2)
Project.unit<0>.triggerChannel<3><0>=uart_control tx_done
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCount<2>=1
Project.unit<0>.triggerMatchCount<3>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchCountWidth<2><0>=0
Project.unit<0>.triggerMatchCountWidth<3><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerMatchType<2><0>=1
Project.unit<0>.triggerMatchType<3><0>=1
Project.unit<0>.triggerPortCount=4
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortIsData<2>=true
Project.unit<0>.triggerPortIsData<3>=true
Project.unit<0>.triggerPortWidth<0>=1
Project.unit<0>.triggerPortWidth<1>=1
Project.unit<0>.triggerPortWidth<2>=3
Project.unit<0>.triggerPortWidth<3>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
